### ISSUE TITLE
webkitwidgets

### ISSUE THREAD

**Issue by swiftgeek** [wd5gnr/qrigol#1]
I had to add webkitwidgets to qrigol.pro in order to compile with qmake && make on archlinux
QT       += core gui webkit webkitwidgets

Package is available on AUR https://aur4.archlinux.org/packages/qrigol-git/

**Comment by wd5gnr** [comment]
Not required for Ubuntu. Interesting. I will try adding it to see if it breaks anything and if not add it. Otherwise will have to figure something out.

**Comment by wd5gnr** [comment]
Actually, I think this is not required for Qt4 but is required for Qt5. I added a conditional inclusion of it for Qt>4. See if that helps.

**Comment by swiftgeek** [comment]
Works for me (qt5)
